Controllers/CRUDController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyLibrary.Context;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// Контроллер для управления книгами в базе данных (CRUD операции).
    /// </summary>
    public class CRUDController : Controller
    {
        private readonly LibraryContext bookContext;

        /// <summary>
        /// Конструктор класса.
        /// </summary>
        /// <param name="bookContext">Контекст базы данных библиотеки.</param>
        public CRUDController(LibraryContext bookContext)
        {
            this.bookContext = bookContext;
        }

        /// <summary>
        /// Отображает страницу CRUD существующих книг.
        /// </summary>
        [Authorize]
        public async Task<IActionResult> Crud()
        {
            ViewBag.Books = await bookContext.Books.ToListAsync();
            return View();
        }

        /// <summary>
        /// Отображает форму создания новой книги.
        /// </summary>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Обрабатывает данные из формы создания книги и добавляет новую книгу в базу данных.
        /// </summary>
        /// <param name="book">Данные новой книги.</param>
        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> Create(Book book)
        {
            Book newBook = new Book()
            {
                Title = book.Title,
                Author = book.Author,
                YearPublishing = book.YearPublishing,
                PublishingHouse = book.PublishingHouse,
                Description = book.Description,
                Image = book.Image,
                UrlBook = book.UrlBook,
                Genre = book.Genre,

            };
            bookContext.Books.Add(newBook);
            await bookContext.SaveChangesAsync();
            return RedirectToAction("List", "Book");
        }

        /// <summary>
        /// Отображает форму подтверждения удаления книги.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно удалить.</param>
        [Authorize]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfDelete(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Удаляет книгу из базы данных.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно удалить.</param>
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                {
                    bookContext.Remove(book);
                    await bookContext.SaveChangesAsync();
                    return RedirectToAction("Crud");
                }
            }
            return NotFound();
        }

        /// <summary>
        /// Отображает форму изменения книги.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно изменить.</param>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Обрабатывает данные из формы редактирования книги и обновляет книгу в базе данных.
        /// </summary>
        /// <param name="book">Данные книги, которые нужно обновить в базе данных.</param>
        /// <returns>Перенаправление на страницу CRUD после успешного обновления.</returns>

        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> Edit(Book book)
        {
            bookContext.Books.Update(book);
            await bookContext.SaveChangesAsync();
            return RedirectToAction("Crud");
        }

        /// <summary>
        /// Отображает подробные сведения о книге с заданным идентификатором.
        /// </summary>
        /// <param name="id">Идентификатор книги, для которой нужно отобразить подробности.</param>
        /// <returns>Представление с подробными сведениями о книге.</returns>
        public async Task<IActionResult> Deteils(int id)
        {
            if (id != null)
            {
                Book book = bookContext.Books.Include(b => b.Genre).SingleOrDefault(b => b.Id == id);
                ViewBag.thisGenre = book.Genre.NameGanre;
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Отображает PDF-файл из базы данных.
        /// </summary>
        /// <param name="filePath">Путь к PDF-файлу в базе данных.</param>
        public ActionResult OpenPdfFromDb(string filePath)
        {
            string decodedFilePath = Uri.UnescapeDataString(filePath);

            var pdfFile = bookContext.Books.FirstOrDefault(f => f.UrlBook == decodedFilePath);

            if (pdfFile != null && pdfFile.UrlBook != null && pdfFile.UrlBook.Length > 0)
            {
                Response.ContentType = "application/pdf";
                string fileName = Path.GetFileName(decodedFilePath);
                Response.Headers["Content-Disposition"] = $"inline; filename={fileName}";
                return File(pdfFile.UrlBook, "application/pdf");
            }
            else
            {
                return Content("Файл не найден");
            }
        }
    }
}

Controllers/UserBookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyLibrary.Context;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// Контроллер для управления книгами, добавленными пользователями в их список "Мои книги".
    /// </summary>
    [Authorize]
    public class UserBookController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly LibraryContext libraryContext;

        /// <summary>
        /// Конструктор класса.
        /// </summary>
        /// <param name="userManager">Менеджер пользователей.</param>
        /// <param name="libraryContext">Контекст базы данных библиотеки.</param>
        public UserBookController(UserManager<User> userManager, LibraryContext libraryContext)
        {
            this.userManager = userManager;
            this.libraryContext = libraryContext;
        }

        /// <summary>
        /// Отображает список книг, добавленных текущим пользователем в их список "Мои книги".
        /// </summary>
        /// <returns>Представление со списком книг пользователя.</returns>
        public async Task<IActionResult> MyBook()
        {
            var user = await userManager.GetUserAsync(User);
            var books = await libraryContext.UserBooks.Where(b => b.UserId == user.Id).Include(b => b.Book).ToListAsync();

            return View(books);
        }

        /// <summary>
        /// Добавляет выбранную книгу в список "Мои книги" текущего пользователя.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно добавить в список "Мои книги".</param>
        /// <returns>Перенаправление на страницу со списком "Мои книги" после успешного добавления.</returns>
        public async Task<IActionResult> AddToUserBook(int id)
        {
            User user = await userManager.GetUserAsync(User);
            Book selectedBook = await libraryContext.Books.SingleOrDefaultAsync(b => b.Id == id);

            if (selectedBook != null)
            {
                var userBook = new UserBook
                {
                    UserId = user.Id,
                    BookId = selectedBook.Id,
                };

                libraryContext.UserBooks.Add(userBook);
                await libraryContext.SaveChangesAsync();
                return RedirectToAction("MyBook");
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Views/Shared/AllBookPage.cshtml
@model Book
<div class="col-lg-4" align="center">
    <a asp-action="Deteils" asp-controller="CRUD" asp-route-id="@Model.Id"><img class="img-thumbnail" width="200" height="300" src="@Model.Image" alt="@Model.Title" /></a>
    <h4 align="center">@Model.Title</h4>
    <p><a class="btn btn-warning" asp-controller="UserBook" asp-action="AddToUserBook" asp-route-id="@Model.Id">Добавить в мою библиотеку</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyLibrary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CRUD" asp-action="Crud">CRUD</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserBook" asp-action="MyBook">Мои книги</a>
                            </li>
                            <li><p>@User.Identity.Name</p></li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input type="submit" value="Выход" />
                            </form>
                        }
                        else
                        {
                            <li class="nav-item" align="right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                            </li>
                            <li class="nav-item" align="right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyLibrary
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>