Controllers/CRUDController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyLibrary.Context;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// Контроллер для управления книгами в базе данных (CRUD операции).
    /// </summary>
    public class CRUDController : Controller
    {
        private readonly LibraryContext bookContext;

        /// <summary>
        /// Конструктор класса.
        /// </summary>
        /// <param name="bookContext">Контекст базы данных библиотеки.</param>
        public CRUDController(LibraryContext bookContext)
        {
            this.bookContext = bookContext;
        }

        /// <summary>
        /// Отображает страницу CRUD существующих книг.
        /// </summary>
        [Authorize]
        public async Task<IActionResult> Crud()
        {
            ViewBag.Books = await bookContext.Books.ToListAsync();
            return View();
        }

        /// <summary>
        /// Отображает форму создания новой книги.
        /// </summary>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Обрабатывает данные из формы создания книги и добавляет новую книгу в базу данных.
        /// </summary>
        /// <param name="book">Данные новой книги.</param>
        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> Create(Book book)
        {
            Book newBook = new Book()
            {
                Title = book.Title,
                Author = book.Author,
                YearPublishing = book.YearPublishing,
                PublishingHouse = book.PublishingHouse,
                Description = book.Description,
                Image = book.Image,
                UrlBook = book.UrlBook,
                Genre = book.Genre,

            };
            bookContext.Books.Add(newBook);
            await bookContext.SaveChangesAsync();
            return RedirectToAction("List", "Book");
        }

        /// <summary>
        /// Отображает форму подтверждения удаления книги.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно удалить.</param>
        [Authorize]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfDelete(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Удаляет книгу из базы данных.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно удалить.</param>
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                {
                    bookContext.Remove(book);
                    await bookContext.SaveChangesAsync();
                    return RedirectToAction("Crud");
                }
            }
            return NotFound();
        }

        /// <summary>
        /// Отображает форму изменения книги.
        /// </summary>
        /// <param name="id">Идентификатор книги, которую нужно изменить.</param>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id != null)
            {
                Book book = await bookContext.Books.SingleOrDefaultAsync(b => b.Id == id);
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Обрабатывает данные из формы редактирования книги и обновляет книгу в базе данных.
        /// </summary>
        /// <param name="book">Данные книги, которые нужно обновить в базе данных.</param>
        /// <returns>Перенаправление на страницу CRUD после успешного обновления.</returns>

        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> Edit(Book book)
        {
            bookContext.Books.Update(book);
            await bookContext.SaveChangesAsync();
            return RedirectToAction("Crud");
        }

        /// <summary>
        /// Отображает подробные сведения о книге с заданным идентификатором.
        /// </summary>
        /// <param name="id">Идентификатор книги, для которой нужно отобразить подробности.</param>
        /// <returns>Представление с подробными сведениями о книге.</returns>
        public async Task<IActionResult> Deteils(int id)
        {
            if (id != null)
            {
                Book book = bookContext.Books.Include(b => b.Genre).SingleOrDefault(b => b.Id == id);
                ViewBag.thisGenre = book.Genre.NameGanre;
                if (book != null)
                    return View(book);
            }
            return NotFound();
        }

        /// <summary>
        /// Отображает PDF-файл из базы данных.
        /// </summary>
        /// <param name="filePath">Путь к PDF-файлу в базе данных.</param>
        public ActionResult OpenPdfFromDb(string filePath)
        {
            string decodedFilePath = Uri.UnescapeDataString(filePath);

            var pdfFile = bookContext.Books.FirstOrDefault(f => f.UrlBook == decodedFilePath);

            if (pdfFile != null && pdfFile.UrlBook != null && pdfFile.UrlBook.Length > 0)
            {
                Response.ContentType = "application/pdf";
                string fileName = Path.GetFileName(decodedFilePath);
                Response.Headers["Content-Disposition"] = $"inline; filename={fileName}";
                return File(pdfFile.UrlBook, "application/pdf");
            }
            else
            {
                return Content("Файл не найден");
            }
        }
    }
}

Controllers/ReviewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyLibrary.Context;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// Контроллер для управления отзывами о книгах.
    /// </summary>
    [Authorize]
    public class ReviewController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly LibraryContext libraryContext;

        /// <summary>
        /// Конструктор класса.
        /// </summary>
        /// <param name="userManager">Менеджер пользователей.</param>
        /// <param name="libraryContext">Контекст базы данных библиотеки.</param>
        public ReviewController(UserManager<User> userManager, LibraryContext libraryContext)
        {
            this.userManager = userManager;
            this.libraryContext = libraryContext;
        }

        /// <summary>
        /// Отображает отзывы о книге с заданным идентификатором.
        /// </summary>
        /// <param name="id">Идентификатор книги, для которой нужно отобразить отзывы.</param>
        /// <returns>Представление с отзывами о книге.</returns>
        public async Task<IActionResult> ShowReview(int id)
        {
            var reviews = await libraryContext.Reviews.Where(r => r.BookId == id).ToListAsync();
            ViewBag.Book = libraryContext.Books.SingleOrDefault(b => b.Id == id);
            ViewBag.User = await userManager.GetUserAsync(User);
            return View(reviews);
        }

        /// <summary>
        /// Отображает форму для добавления нового отзыва о книге с заданным идентификатором.
        /// </summary>
        /// <param name="id">Идентификатор книги, для которой нужно добавить отзыв.</param>
        /// <returns>Представление формы добавления отзыва.</returns>
        public async Task<IActionResult> AddReview(int id)
        {
            ViewBag.User = await userManager.GetUserAsync(User);
            ViewBag.Book = libraryContext.Books.SingleOrDefault(b => b.Id == id);
            return View();
        }

        /// <summary>
        /// Обрабатывает данные из формы добавления отзыва и добавляет новый отзыв о книге в базу данных.
        /// </summary>
        /// <param name="review">Данные нового отзыва о книге.</param>
        /// <returns>Перенаправление на страницу с отзывами после успешного добавления.</returns>
        [HttpPost]
        public async Task<IActionResult> AddReview(Review review)
        {
            var newReview = new Review()
            {
                Comment = review.Comment,
                UserId = review.UserId,
                BookId = review.BookId
            };

            libraryContext.Reviews.Add(newReview);
            await libraryContext.SaveChangesAsync();
            return View("ShowReview");
        }
    }
}

Views/CRUD/Create.cshtml
@model MyLibrary.Models.Book
@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" asp-controller="CRUD">
    <p>
        <label asp-for="Title">Название книги</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Author">Автор</label><br />
        <input type="text" asp-for="Author" />
    </p>
    <p>
        <label asp-for="Genre">Номер жанра</label><br />
        <input type="value" asp-for="Genre" />
    </p>
    <p>
        <label asp-for="YearPublishing">Год публикации</label><br />
        <input type="text" asp-for="YearPublishing" />
    </p>
    <p>
        <label asp-for="PublishingHouse">Издание</label><br />
        <input type="text" asp-for="PublishingHouse" />
    </p>
    <p>
        <label asp-for="Description">Описание</label><br />
        <input type="text" asp-for="Description" />
    </p>
    <p>
        <label asp-for="Image">Изображение</label><br />
        <input type="text" asp-for="Image" />
    </p>
    <p>
        <label asp-for="UrlBook">Ссылка на прочтение книги</label><br />
        <input type="text" asp-for="UrlBook" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

Views/CRUD/Crud.cshtml
@model MyLibrary.Models.Book
@{
    ViewData["Title"] = "Crud";
}

<h1>Crud</h1>
<table class="table">
    <tr>
        <th>Номер книги</th>
        <th>Название книги</th>
    </tr>
    @foreach (var item in ViewBag.Books)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Title</td>
            <td><a asp-action="Edit" asp-controller="CRUD" asp-route-id="@item.Id">Изменить</a></td>
            <td><a asp-action="Delete" asp-controller="CRUD" asp-route-id="@item.Id">Удалить</a></td>
        </tr>
    }
</table>
<a asp-area="" asp-controller="CRUD" asp-action="Create">Добавить книгу</a>

Views/CRUD/Delete.cshtml
@model MyLibrary.Models.Book
@{
    ViewData["Title"] = "Delete";
}

<h1>Delite</h1>

<div>
    <dl class="dl-horizontal">
        <dt>Номер</dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    <div>
        <form asp-controller="CRUD" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" value="Удалить" />
            </div>
        </form>
    </div>
</div>

Views/CRUD/Deteils.cshtml
@model MyLibrary.Models.Book
@{
    ViewData["Title"] = Model.Title;
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книга</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            text-align: center;
        }

        .book-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .book-image {
            max-width: 100%;
            margin-bottom: 20px;
        }

        .book-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .book-details {
            font-size: 18px;
            margin-bottom: 20px;
        }

        .read-link {
            display: block;
            font-size: 18px;
            text-decoration: none;
            color: #007bff;
            margin-top: 10px;
        }
    </style>
</head>

<body>  
    <div class="book-container">
        <img src="@Model.Image" alt="@Model.Title" width="200" height="300" class="book-image">
        <div class="book-title">@Model.Title</div>
        <div class="book-details">
            <p><strong>Жанр:</strong> @Model.Genre.NameGanre</p>
            <p><strong>Описание:</strong> @Model.Description</p>
            <p><strong>Год издания:</strong> @Model.YearPublishing г.</p>
            <p><strong>Издательство:</strong> @Model.PublishingHouse</p>
        </div>
        <a href="@Url.Action("OpenPdfFromDb", "CRUD", new { filePath = Model.UrlBook })" target="_blank" class="read-link">Прочитать книгу</a>
        <a class="read-link" asp-controller="Review" asp-action="ShowReview" asp-route-id="@Model.Id">Отзывы и оценка</a>
    </div>
</body>

Views/CRUD/Edit.cshtml
@model MyLibrary.Models.Book
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form asp-action="edit" asp-controller="CRUD" method="post" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Title">Название книги</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Author">Автор</label><br />
        <input type="text" asp-for="Author" />
    </p>
    <p>
        <label asp-for="Genre">Номер жанра</label><br />
        <input type="value" asp-for="Genre" />
    </p>
    <p>
        <label asp-for="YearPublishing">Год публикации</label><br />
        <input type="text" asp-for="YearPublishing" />
    </p>
    <p>
        <label asp-for="PublishingHouse">Издание</label><br />
        <input type="text" asp-for="PublishingHouse" />
    </p>
    <p>
        <label asp-for="Description">Описание</label><br />
        <input type="text" asp-for="Description" />
    </p>
    <p>
        <label asp-for="Image">Изображение</label><br />
        <input type="text" asp-for="Image" />
    </p>
    <p>
        <label asp-for="UrlBook">Ссылка на прочтение книги</label><br />
        <input type="text" asp-for="UrlBook" />
    </p>
    <p><input type="submit" value="Сохранить" /></p>
</form>